---
# tasks file for challenge
- name: update motd
  lineinfile: 
    line: 'Provisioned by ansible!'
    dest: /etc/motd
    create: yes
    state: present

# - name: Update apt-cache 
#   apt: update_cache=yes

- name: Install Nginx
  apt: name=nginx state=latest 

- name: Sets Nginx conf file
  template:
    src: "files/nginx.conf.j2"
    dest: "/etc/nginx/sites-available/{{ http_conf }}"

- name: Enables new site
  file:
    src: "/etc/nginx/sites-available/{{ http_conf }}"
    dest: "/etc/nginx/sites-enabled/{{ http_conf }}"
    state: link
  notify: Reload Nginx

- name: Removes "default" site
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: Reload Nginx


